from .value_function.discrete_value_function import DiscreteValueFunction
from .value_function.regression_value_function import RegressionValueFunction
from .value_function.modified_for_stopping import ModifiedForStopping
